language: python

python:
  - "2.7"



# fix travis phantomjs to 1.9.1
before_install:
  - wget http://phantomjs.googlecode.com/files/phantomjs-1.9.1-linux-x86_64.tar.bz2
  - tar xjf phantomjs-1.9.1-linux-x86_64.tar.bz2
  - sudo rm -rf /usr/local/phantomjs
  - sudo mv  phantomjs-1.9.1-linux-x86_64 /usr/local/phantomjs





# command to install dependencies
install:
  - pip install -r pip-requirements.txt --use-mirrors
  - pip install coveralls --use-mirrors
  - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm

before_script:
  - psql -c 'create database ejrf;' -U postgres
  - cp eJRF/travis-settings.py eJRF/localsettings.py
  - python manage.py syncdb --noinput
  - python manage.py migrate
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - gem install travis-artifacts

# command to run tests
script:
  - coverage run manage.py test
  - python manage.py harvest

after_success:
  - coveralls

after_failure:
  - tar -cvzf screenshots-$TRAVIS_BUILD_ID-$TRAVIS_JOB_ID.tar.gz screenshots
  - travis-artifacts upload --path screenshots-$TRAVIS_BUILD_ID-$TRAVIS_JOB_ID.tar.gz
